name: Manually Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Check if actor is repo owner
      run: |
        if [ "${{ github.repository_owner }}" != "LLM-Evaluation-s-Always-Fatiguing" ]; then
          echo "Error: Only the repository owner can run this workflow."
          exit 1
        fi
    # checkout to main branch
    - uses: actions/checkout@v3
      with:
        ref: main
    # setup python 3.10
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Build with Poetry
      run: poetry build

    - name: Determine package version
      id: package_version
      run: |
        echo "tag_name=v$(poetry version -s)"
        echo ::set-output name=tag_name::$(poetry version -s)

    - name: Create Release Draft
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package_version.outputs.tag_name }}
        release_name: Release v${{ steps.package_version.outputs.tag_name }}
        draft: true
        prerelease: false

#    - name: Publish package to PyPI
#      uses: pypa/gh-action-pypi-publish@v1.4.2
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
#        packages_dir: dist
#        package_types: sdist
